### PR TITLE
fix(web): eliminate dark mode SSR flicker

### LINKED ISSUE #33: 📎 Reduce the flickering in dark mode

### PR DESCRIPTION
**Pull request by sruenwg**
Fixes #33.

On dark mode, hard navigation (including refresh) should no longer show a flash of light mode styling.
This fix replaces MUI's ThemeProvider with CssVarsProvider and largely follows [their documented migration guide](https://mui.com/material-ui/experimental-api/css-theme-variables/).

This required [changing the pattern](https://mui.com/material-ui/experimental-api/css-theme-variables/migration/#4-refactor-custom-styles-to-use-the-attribute-selector) for styling components based on the current mode.
```
// Previous
cssAttribute: theme.palette.mode === "dark" ? darkModeValue : lightModeValue

// New
cssAttribute: lightModeValue,
[theme.getColorSchemeSelector("dark")]: {
  cssAttribute: darkModeValue,
},
```

Also, since the `theme` object always contains light mode values on the server, SSRed components now rely on CSS variables for theme variables (i.e. `theme.palette` has been changed to `theme.vars.palette` — see [here](https://mui.com/material-ui/experimental-api/css-theme-variables/usage/#using-theme-variables) for details).

I did a manual check of all the components with code changes and believe that the styling looks identical to the previous version. Below are some clips for reference.

https://github.com/sugar-cat7/vspo-portal/assets/155891765/7bd7e584-872e-440c-ad7e-3f9cb9cae067

https://github.com/sugar-cat7/vspo-portal/assets/155891765/82152a4b-3381-479c-a2e1-b3aae451538f

https://github.com/sugar-cat7/vspo-portal/assets/155891765/deff75e5-d73b-422c-b287-6a0ffbd308e5

### CODE REVIEW

File: service/vspo-schedule/web/src/pages/_document.tsx [hunk 1]
```diff
@@ -30,6 +31,7 @@ class MyDocument extends Document {
           <meta name="theme-color" content="#fff" />
         </Head>
         <body>
+          {getInitColorSchemeScript()}
```
Comment (sugar-cat7) [inline service/vspo-schedule/web/src/pages/_document.tsx:34]: When using prefers-color-scheme, do you need to set defaultMode to system?

**Review by sugar-cat7 — APPROVED** [review]
LGTM :)

File: service/vspo-schedule/web/src/pages/_document.tsx (hunk 1 above)
Comment (sugar-cat7) [reply service/vspo-schedule/web/src/pages/_document.tsx:34]: I understand. Thank you for the detailed explanation :)

**Review by sugar-cat7 — APPROVED** [review]
