### PR TITLE
fix: switch fallback true

### LINKED ISSUE #281: 🐛 BUG: New `/schedule/[date]` paths seem only to be generated on build
### What operating system are you using?

Mac

### Describe the Bug

Currently (2024/03/24 09:00 UTC), navigating to `/schedule/2024-03-24` returns a 404 despite `/schedule/all` clearly showing multiple streams for 03/24.
`/schedule/all` also shows a tab for 03/26, but navigating to `/schedule/2024-03-26` similarly returns a 404.

I expect all nearby dates with streams to be navigable (i.e. to have a valid path `/schedule/[date]`), and I expect all visible date tabs to be navigable.

Looking at `[status].tsx`'s `getStaticPaths`, it seems the intended behavior is for all dates within ±5 days from the current date to be navigable.
However, the actual paths I am currently able to navigate to are from 03-13 to 03-23 (with 03-13 to 03-18 highlighting the incorrect tab in the date tabs).
My suspicion is that this is because the repo was last updated on 03-18 and that was when `getStaticPaths` was last run.
If this is the case, setting `fallback: true` might be a sufficient fix for this issue (though older pages >5 days in the past would still be served until the next build).

https://github.com/sugar-cat7/vspo-portal/assets/155891765/d549c7ba-44ae-4eac-89be-4c59c30ecdf6

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by sugar-cat7**
Fixes #281 

**What this PR solves / how to test:**

Due to inadvertently disabling the regular deployment process running in the background, pages that were supposed to exist became inaccessible.

To address this, the following actions were taken:
- Re-establishing the deploy hook and the regular deployment schedule.
- Setting fallback: true <- This PR

[The impact of this change]
Currently, the API returns more Livestreams than the dates displayed on the tab, allowing some pages to be viewed even on dates not displayed on the tabs. However, this is more of an issue on the API side rather than the frontend. Therefore, in the process of replacing the API, we will make corrections to ensure the Livestreams are returned for the correct dates.

### CODE REVIEW

File: service/vspo-schedule/web/src/pages/schedule/[status].tsx [hunk 1]
```diff
@@ -56,6 +58,11 @@ const HomePage: NextPageWithLayout<LivestreamsProps> = ({
   eventsByDate,
   dateTabsInfo,
 }) => {
+  const router = useRouter();
+  if (router.isFallback) {
+    return <Loading />;
+  }
```
Comment (sugar-cat7) [inline service/vspo-schedule/web/src/pages/schedule/[status].tsx:64]: Avoiding `props` becoming undefined during prebuild

https://nextjs.org/docs/pages/api-reference/functions/get-static-paths#fallback-pages
