### PR TITLE
fix(web): move padding from theme toggle button's parent element to i…

### LINKED ISSUE #164: 🐛 BUG: Theme toggle has confusing click area
### What operating system are you using?

Mac

### Describe the Bug

The theme toggle button does not register clicks near its periphery, especially on the right side (see clip).
This is annoying/confusing since (1) the cursor changing to a pointer 👆 on hover, (2) the button area turning grey on hover, and (3) the ripple animation playing on click all indicate to the user that the button should be clickable in that spot.
I expect these indicators to align with the actual click area which performs the theme toggle action.

https://github.com/sugar-cat7/vspo-portal/assets/155891765/d952a3ac-e339-4d37-a4ff-3dc621bcbccc

(Afaik this is the only button on the site with this behaviour.)

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by ss77995ss**
Fixes #164 

**What this PR solves / how to test:**
* The confusing area is caused by the **padding** from `<MenuItem>` and `<FormControlLabel>` default **margin-right**
* Move the padding to `<FormControlLabel>` to remain the original UI and remove the confusing area
* How to test: Click the edge area of the theme toggle button and check whether the toggle event trigger

https://github.com/sugar-cat7/vspo-portal/assets/28031139/e3511201-0bf1-4a0b-8e9e-16b458f69395

### CODE REVIEW

**Comment by sugar-cat7** [comment]
Thank you for your contribution! If you add me as a reviewer, I'll check the pull request :)

**Comment by ss77995ss** [comment]
@sugar-cat7 Thanks for your reply! However, I could not assign anyone as a reviewer and I don't know why :(
Screenshot 2024-02-14 at 11 01 04

**Comment by sugar-cat7** [comment]
> @sugar-cat7 Thanks for your reply! However, I could not assign anyone as a reviewer and I don't know why :( Screenshot 2024-02-14 at 11 01 04

I see, maybe it's because it's a forked repository? I've added a code owner for now, so I think it will be automatically assigned from the next time!

File: service/vspo-schedule/web/src/components/Elements/Button/ThemeToggleButton.tsx [hunk 1]
```diff
@@ -76,6 +76,10 @@ export const ThemeToggleButton: React.FC = () => {
   return (
     <FormGroup>
       <FormControlLabel
+        style={{
+          marginRight: 0,
+          padding: '6px 24px',
+        }}
```
Comment (sugar-cat7) [inline service/vspo-schedule/web/src/components/Elements/Button/ThemeToggleButton.tsx:82]: Regarding MUI components, please use sx props instead of inline styles🙏.
https://mui.com/system/getting-started/the-sx-prop/#theme-aware-properties

(Sorry for the parts that already use style. I will create a separate issue to replace them.)

Comment (ss77995ss) [reply service/vspo-schedule/web/src/components/Elements/Button/ThemeToggleButton.tsx:82]: 👌 ! Should I also use **aliases** for `spacing` property? (ref: https://mui.com/system/getting-started/the-sx-prop/#spacing)
For example:
```diff
- marginRight: 0;
- padding: "6px 24px";
+ mr: 0;
+ p: 0;
```

Comment (sugar-cat7) [reply service/vspo-schedule/web/src/components/Elements/Button/ThemeToggleButton.tsx:82]: Yes! I would like to actively use aliases for spacing properties if possible.

Comment (ss77995ss) [reply service/vspo-schedule/web/src/components/Elements/Button/ThemeToggleButton.tsx]: No problem 👍 Just update a new commit 87b7c4867b988f16cca2c1449c244c4fc9adadbf for this PR. Have a look!

**Review by sugar-cat7 — APPROVED** [review]
Thank you :)

**Comment by ss77995ss** [comment]
I saw the discussion in https://github.com/sugar-cat7/vspo-portal/issues/190#issuecomment-1947587307
I'll change the aliases before merge!
BTW, I don't have the permission to merge the PR by myself. Not sure why? Maybe it is from forked repo again.
Sorry for the inconvenient :(

**Comment by sugar-cat7** [comment]
@ss77995ss 
I've added you as a collaborator, feel free to merge if it looks good to you. :)
(It's okay to ignore the CI)
